name: Lint

# If a pull-request is pushed then cancel all previously running jobs related
# to that pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master

env:
  PY_COLORS: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
      - run: pip install --upgrade tox
      - name: Run commitizen (https://commitizen-tools.github.io/commitizen/)
        run: tox -e cz
      - name: Run black code formatter (https://black.readthedocs.io/en/stable/)
        run: tox -e black -- --check
      - name: Run flake8 (https://flake8.pycqa.org/en/latest/)
        run: tox -e flake8
      - name: Run mypy static typing checker (http://mypy-lang.org/)
        run: tox -e mypy
      - name: Run isort import order checker (https://pycqa.github.io/isort/)
        run: tox -e isort -- --check
      - name: Run pylint Python code static checker (https://github.com/PyCQA/pylint)
        run: tox -e pylint
      - name: Ensure no merge-commits in the Pull Request (PR)
        if: github.event_name == 'pull_request'
        run: |
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "HEAD_SHA: ${HEAD_SHA}"
          MERGE_COMMITS=$(git rev-list --merges origin/${GITHUB_BASE_REF}..${HEAD_SHA})
          if [[ -n "${MERGE_COMMITS}" ]]; then
            echo "ERROR: The Pull Request (PR) contains a 'merge commit': ${MERGE_COMMITS}"
            exit 1
          fi
